name: 'Android Kernel Build Action'
description: "An action to build android kernel."

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  kernel-url:
    description: 'URL of the Android kernel source repository'
    required: true
  kernel-branch:
    description: 'Branch name of the main kernel source repository'
    required: false
    default: main
  kernel-dir:
    description: 'Directory name for storing kernel source code'
    required: false
    default: kernel
  depth:
    description: 'Git clone depth for faster downloads'
    required: false
    default: '1'
  config:
    description: 'Name of the kernel configuration file to use'
    required: true
    default: defconfig
  arch:
    description: 'Target CPU architecture for cross-compilation'
    required: true
    default: arm64
  android-version:
    description: 'Android version for AOSP toolchain selection'
    required: false
    default: ''
  vendor:
    description: 'Enable vendor kernel source code integration'
    required: false
    default: 'false'
  vendor-url:
    description: 'URL of the vendor kernel source repository'
    required: false
  vendor-branch:
    description: 'Branch name of the vendor kernel source repository'
    required: false
    default: main
  vendor-dir:
    description: 'Directory name for storing vendor kernel source'
    required: false
    default: vendor
  aosp-clang:
    description: 'Use AOSP Clang toolchain'
    required: false
    default: 'false'
  aosp-clang-version:
    description: 'Version of AOSP Clang toolchain to use'
    required: false
    default: r383902
  aosp-gcc:
    description: 'Use AOSP GCC toolchain'
    required: false
    default: 'false'
  other-clang-url:
    description: 'URL of custom Clang toolchain'
    required: false
  other-clang-branch:
    description: 'Branch of the custom Clang toolchain'
    required: false
    default: main
  other-gcc64-url:
    description: 'URL of custom 64-bit GCC toolchain'
    required: false
  other-gcc64-branch:
    description: 'Branch of custom 64-bit GCC toolchain'
    required: false
    default: main
  other-gcc32-url:
    description: 'URL of custom 32-bit GCC toolchain'
    required: false
  other-gcc32-branch:
    description: 'Branch of custom 32-bit GCC toolchain'
    required: false
    default: main
  ksu:
    description: 'Enable KernelSU integration'
    required: false
    default: 'false'
  ksu-version:
    description: 'Version of KernelSU to integrate'
    required: false
    default: main
  ksu-lkm:
    description: 'Build KernelSU as a loadable kernel module'
    required: false
    default: 'false'
  ksu-other:
    description: 'Use a third-party KernelSU fork'
    required: false
    default: 'false'
  ksu-url:
    description: 'URL of the third-party KernelSU fork'
    required: false
  rekernel:
    description: 'Enable Re-Kernel support'
    required: false
    default: 'false'
  nethunter:
    description: 'Enable Kali NetHunter support'
    required: false
    default: 'false'
  nethunter-patch:
    description: 'Apply NetHunter-specific patches'
    required: false
    default: 'false'
  lxc:
    description: 'Enable LXC/Docker container support'
    required: false
    default: 'false'
  lxc-patch:
    description: 'Apply LXC-specific patches'
    required: false
    default: 'false'
  kvm:
    description: 'Enable KVM (Kernel Virtual Machine) support'
    required: false
    default: 'false'
  bbg:
    description: 'Enable BaseBandGuard support'
    required: false
    default: 'false'
  disable-lto:
    description: 'Disable Link Time Optimization (LTO)'
    required: false
    default: 'false'
  ccache:
    description: 'Enable ccache compilation cache'
    required: false
    default: 'false'
  anykernel3:
    description: 'Use AnyKernel3 packaging method'
    required: false
    default: 'false'
  anykernel3-url:
    description: 'URL of custom AnyKernel3 repository'
    required: false
  bootimg-url:
    description: 'URL to download the original boot.img file'
    required: false
  release:
    description: 'Automatically create a GitHub Release'
    required: false
    default: 'false'
  access-token:
    description: 'GitHub personal access token for releases'
    required: false
  extra-make-args:
    description: 'Additional make arguments in JSON array format'
    required: false
    default: '[]'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: 'always()'